# Generated by Django 2.2 on 2019-04-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StatsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('atleta1', models.BooleanField(default=True)),
                ('atleta2', models.BooleanField(default=True)),
                ('zonaCampo', models.BooleanField(default=True)),
                ('zonaBaliza', models.BooleanField(default=True)),
                ('novoinstante', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='convocado',
            old_name='emcampo',
            new_name='emCampo',
        ),
        migrations.AddField(
            model_name='tecnico',
            name='grelhaBaliza',
            field=models.CharField(default='aa', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnico',
            name='grelhaCampo',
            field=models.CharField(default='aa', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StatsApp.TipoEvento'),
        ),
        migrations.CreateModel(
            name='TiposSelecionados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StatsApp.Tecnico')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StatsApp.TipoEvento')),
            ],
        ),
    ]
