# Generated by Django 3.0.dev20190409205233 on 2019-04-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatsApp', '0002_auto_20190410_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='grelhaBaliza',
            field=models.CharField(default='3x3', max_length=5),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='grelhaCampo',
            field=models.CharField(default='8x4', max_length=5),
        ),
    ]
