INSERT INTO "public"."server_tipoevento" ("id", "tipo", "atleta1", "atleta2", "zonaCampo", "zonaBaliza", "novoinstante", "equipa") VALUES ('0', 'Golo', 't', 'f', 't', 't', 'f', 't'),
('1', 'Remate à baliza', 't', 'f', 't', 't', 'f', 't'),
('2', 'Remate intercetado', 't', 'f', 't', 'f', 'f', 't'),
('3', 'Remate fora', 't', 'f', 't', 'f', 'f', 't'),
('4', 'Substituição', 't', 't', 'f', 'f', 'f', 't'),
('5', 'Perda de bola', 't', 'f', 't', 'f', 'f', 't'),
('6', 'Roubo de bola', 't', 'f', 't', 'f', 'f', 't'),
('7', 'Cartão azul', 't', 'f', 't', 'f', 'f', 't'),
('8', 'Cartão vermelho', 't', 'f', 't', 'f', 'f', 't'),
('9', 'Erro próprio', 't', 'f', 't', 'f', 'f', 't'),
('10', 'Powerplay', 'f', 'f', 'f', 'f', 'f', 't'),
('11', 'Fim de Powerplay', 'f', 'f', 'f', 'f', 'f', 't'),
('12', 'Livre Direto', 't', 'f', 't', 'f', 'f', 't'),
('13', 'Penalti', 't', 'f', 't', 'f', 'f', 't'),
('14', 'Golpe duplo', 'f', 'f', 't', 'f', 'f', 'f'),
('15', 'Time-out', 'f', 'f', 'f', 'f', 'f', 't'),
('16', 'Alterar relógio', 'f', 'f', 'f', 'f', 't', 'f'),
('17', 'Ataque organizado', 'f', 'f', 'f', 'f', 'f', 't'),
('18', 'Ataque rápido', 'f', 'f', 'f', 'f', 'f', 't'),
('19', 'Contra-ataque', 'f', 'f', 'f', 'f', 'f', 't'),
('20', 'Falta', 't', 'f', 't', 'f', 'f', 't');
