# Generated by Django 2.1.7 on 2019-03-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Clube')),
            ],
            options={
                'verbose_name_plural': 'Gestores',
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='formacao',
            options={'verbose_name_plural': 'Formações'},
        ),
        migrations.AddField(
            model_name='jogo',
            name='adversario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Formacao'),
        ),
    ]
