# Generated by Django 2.1.7 on 2019-03-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_atleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cor', models.CharField(max_length=6)),
                ('simbolo', models.TextField()),
            ],
        ),
    ]
