# Generated by Django 2.1.7 on 2019-03-14 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190314_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='formacao',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='Minhaequipa', to='polls.Formacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jogo',
            name='adversario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Adversário', to='polls.Formacao'),
        ),
    ]
