# Generated by Django 2.1.7 on 2019-03-14 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190314_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('formacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Formacao')),
            ],
            options={
                'verbose_name_plural': 'Técnicos',
            },
        ),
        migrations.AddField(
            model_name='jogo',
            name='casafora',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='tecnico',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='polls.Tecnico'),
            preserve_default=False,
        ),
    ]
