# Generated by Django 2.2 on 2019-05-02 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('licenca', models.IntegerField()),
                ('camisola', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cor', models.CharField(max_length=7)),
                ('simbolo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Clube')),
            ],
            options={
                'verbose_name_plural': 'Formações',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('grelhaCampo', models.CharField(default='8x4', max_length=5)),
                ('grelhaBaliza', models.CharField(default='3x3', max_length=5)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Clube')),
            ],
            options={
                'verbose_name_plural': 'Técnicos',
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('atleta1', models.BooleanField(default=True)),
                ('atleta2', models.BooleanField(default=True)),
                ('zonaCampo', models.BooleanField(default=True)),
                ('zonaBaliza', models.BooleanField(default=True)),
                ('novoinstante', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiposSelecionados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Tecnico')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.TipoEvento')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('casa', models.BooleanField(default=True)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('grelhaCampo', models.CharField(max_length=5)),
                ('grelhaBaliza', models.CharField(max_length=5)),
                ('adversario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adversario', to='server.Formacao')),
                ('formacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhaequipa', to='server.Formacao')),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Clube')),
            ],
            options={
                'verbose_name_plural': 'Gestores',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zonaCampo', models.IntegerField(blank=True, default=None, null=True)),
                ('zonaBaliza', models.IntegerField(blank=True, default=None, null=True)),
                ('instante', models.TimeField()),
                ('novoinstante', models.TimeField(blank=True, default=None, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('atleta1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AtletaEntra', to='server.Atleta')),
                ('atleta2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AtletaSai', to='server.Atleta')),
                ('equipa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Formacao')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Jogo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.TipoEvento')),
            ],
        ),
        migrations.CreateModel(
            name='Convocado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emCampo', models.BooleanField(default=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Atleta')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Jogo')),
            ],
        ),
        migrations.AddField(
            model_name='atleta',
            name='formacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Formacao'),
        ),
    ]
