# Generated by Django 2.2 on 2019-05-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='numero',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoevento',
            name='equipa',
            field=models.BooleanField(default=True),
        ),
    ]
