# Generated by Django 2.2 on 2019-05-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190519_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
