# Generated by Django 2.2.1 on 2019-06-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_jogo_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='parte',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='evento',
            name='sinalizado',
            field=models.BooleanField(default=False),
        ),
    ]
