# Generated by Django 2.2.1 on 2019-06-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_jogo_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='parte',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='evento',
            name='sinalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jogo',
            name='duracao',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='jogo',
            name='partes',
            field=models.IntegerField(default=2),
        ),
    ]
