# Generated by Django 2.1.7 on 2019-06-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20190612_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='convocados',
            field=models.BooleanField(default=True),
        ),
    ]
